{% set name = "liteiclink" %}
{% set version = "2024.08" %}
{% set sha256 = "e41cc411551a7a53c7e670f8bc5d65e7d4e6fad456ba5f9d24a1c2409a3376a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex
    - pyyaml

test:
  imports:
    - liteiclink

about:
  home: https://github.com/enjoy-digital/liteiclink
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable Inter-Chip communication cores
  description: Small footprint and configurable Inter-Chip communication cores
  dev_url: https://github.com/enjoy-digital/liteiclink

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
