{% set name = "liteiclink" %}
{% set version = "2024.12" %}
{% set sha256 = "c1511ecfc84f24d981719c15b639de463eafd4ef76b60141f77cb9ea8a416ff0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - litex ~={{ version }}*
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - liteiclink

about:
  home: https://github.com/enjoy-digital/liteiclink
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable Inter-Chip communication cores
  description: Small footprint and configurable Inter-Chip communication cores
  dev_url: https://github.com/enjoy-digital/liteiclink

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
